hibernate:
  ddl-auto:
    mode: update

spring:
  datasource:
    url: <connection string here>
    username: <username>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    whitelabel:
      enabled: false
